"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Query from "./layoutClient";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { usePathname } from "next/navigation";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = { ${geistSans.variable} ${geistMono.variable}
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Rotas sem barra lateral
  const noSidebarRoutes = ["/", "/login", "/register"];

  return (
    <Query>
      <html lang="en" className="overflow-y-hidden h-[100vh]">
        <body className={` antialiased flex flex-row min-h-screen w-full`}>
          {noSidebarRoutes.includes(pathname) ? null : (
            <aside className="w-64 bg-white shadow-lg">
              <div className="flex flex-col justify-between h-full">
                {/* Navegação */}
                <div className="p-6">
                  <h2 className="text-2xl font-bold text-gray-700 mb-6">
                    Painel
                  </h2>
                  <nav className="space-y-4">
                    <Link href="/painel" className="w-full block">
                      <Button className="w-full justify-start" variant="ghost">
                        Dashboard
                      </Button>
                    </Link>
                    <Link href="/servicos" className="w-full block">
                      <Button className="w-full justify-start" variant="ghost">
                        Serviços
                      </Button>
                    </Link>
                    <Link href="/produtos" className="w-full block">
                      <Button className="w-full justify-start" variant="ghost">
                        Produtos
                      </Button>
                    </Link>
                    <Link href="/almoxarifado" className="w-full block">
                      <Button
                        className="w
                    -full justify-start"
                        variant="ghost"
                      >
                        Almoxarifado
                      </Button>
                    </Link>
                  </nav>
                </div>

                {/* Botão de Logout */}
                <div className="p-6">
                  <Button variant="destructive" className="w-full">
                    Logout
                  </Button>
                </div>
              </div>
            </aside>
          )}

          <main className="w-full overflow-y-hidden">{children}</main>
        </body>
      </html>
    </Query>
  );
}
